import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, MailCheck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { buildApiUrl } from "@/lib/client-api";
import { useClientAuth } from "@/hooks/use-client-auth";

export const Route = createFileRoute("/client/verify-email")({
  head: () => ({
    meta: [
      { title: "Verify Email — Netweavesolutions" },
      {
        name: "description",
        content: "Confirm your email address to activate your Netweavesolutions client account.",
      },
      { name: "robots", content: "noindex" },
    ],
  }),
  component: VerifyEmailPage,
});

function VerifyEmailPage() {
  const { resendVerification } = useClientAuth();
  const [state, setState] = useState<"loading" | "ok" | "error">("loading");
  const [message, setMessage] = useState("Verifying your email address…");
  const [email, setEmail] = useState("");
  const [resending, setResending] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    // Links generated by our own mailer carry `token_hash`; links generated by
    // the Supabase mailer fall back to `token`. Both are accepted.
    const tokenHash = params.get("token_hash") ?? params.get("tokenHash") ?? "";
    const token = params.get("token") ?? "";
    const emailParam = (params.get("email") ?? "").trim();

    if (emailParam) setEmail(emailParam);

    if (!tokenHash && !token) {
      setState("error");
      setMessage(
        "This verification link is missing its token. Request a new one below and we'll email you a fresh link.",
      );
      return;
    }

    let cancelled = false;

    fetch(buildApiUrl("/auth/verify-email"), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        ...(tokenHash ? { tokenHash } : {}),
        ...(token ? { token } : {}),
        ...(emailParam ? { email: emailParam } : {}),
      }),
    })
      .then(async (res) => {
        const data = (await res.json().catch(() => null)) as
          | { error?: string; message?: string; email?: string }
          | null;
        if (!res.ok) {
          throw new Error(data?.error || "We could not verify this link.");
        }
        if (cancelled) return;
        if (data?.email) setEmail(data.email);
        setState("ok");
        setMessage(data?.message || "Your email address is verified. You can sign in now.");
      })
      .catch((error: unknown) => {
        if (cancelled) return;
        setState("error");
        setMessage(
          error instanceof Error
            ? error.message
            : "This verification link is invalid or has expired. Request a new one below.",
        );
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const onResend = async () => {
    const target = email.trim();
    if (!target) {
      toast.error("Enter the email address you registered with.");
      return;
    }
    setResending(true);
    try {
      await resendVerification(target);
      toast.success("If that email needs verification, we've sent a new link.");
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : "We could not send the verification email.",
      );
    } finally {
      setResending(false);
    }
  };

  return (
    <div className="mx-auto flex min-h-[60vh] max-w-md flex-col items-center justify-center px-6 py-16 text-center">
      {state === "loading" ? (
        <>
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="mt-4 text-sm text-muted-foreground">Verifying your email address…</p>
        </>
      ) : state === "ok" ? (
        <>
          <CheckCircle2 className="h-10 w-10 text-primary" />
          <h1 className="mt-4 text-xl font-semibold">Email verified</h1>
          <p className="mt-2 text-sm text-muted-foreground">{message}</p>
          <Button asChild className="mt-6">
            <Link to="/client/login" search={email ? ({ email } as never) : undefined}>
              Continue to sign in
            </Link>
          </Button>
        </>
      ) : (
        <>
          <XCircle className="h-10 w-10 text-destructive" />
          <h1 className="mt-4 text-xl font-semibold">Verification failed</h1>
          <p className="mt-2 text-sm text-muted-foreground">{message}</p>

          <div className="mt-8 w-full space-y-3 rounded-lg border border-border bg-card p-5 text-left">
            <div className="flex items-center gap-2 text-sm font-medium">
              <MailCheck className="h-4 w-4 text-primary" />
              Send a new verification link
            </div>
            <div className="space-y-2">
              <Label htmlFor="verify-resend-email">Registered email</Label>
              <Input
                id="verify-resend-email"
                type="email"
                autoComplete="email"
                placeholder="you@company.com"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
              />
            </div>
            <Button type="button" className="w-full" onClick={onResend} disabled={resending}>
              {resending ? "Sending…" : "Resend verification email"}
            </Button>
          </div>

          <Link to="/client/login" className="mt-6 text-sm text-primary hover:underline">
            Back to sign in
          </Link>
        </>
      )}
    </div>
  );
}
