/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBuilderRouteImport } from './routes/admin.builder'
import { Route as AdminCareersRouteImport } from './routes/admin.careers'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWebsiteRouteImport } from './routes/admin.website'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientActivityRouteImport } from './routes/client.activity'
import { Route as ClientFilesRouteImport } from './routes/client.files'
import { Route as ClientForgotPasswordRouteImport } from './routes/client.forgot-password'
import { Route as ClientInvoicesRouteImport } from './routes/client.invoices'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientMeetingsRouteImport } from './routes/client.meetings'
import { Route as ClientMessagesRouteImport } from './routes/client.messages'
import { Route as ClientNotificationsRouteImport } from './routes/client.notifications'
import { Route as ClientOauthCallbackRouteImport } from './routes/client.oauth-callback'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientProjectsRouteImport } from './routes/client.projects'
import { Route as ClientRegisterRouteImport } from './routes/client.register'
import { Route as ClientRequirementsRouteImport } from './routes/client.requirements'
import { Route as ClientResetPasswordRouteImport } from './routes/client.reset-password'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientSupportRouteImport } from './routes/client.support'
import { Route as ClientVerifyEmailRouteImport } from './routes/client.verify-email'
import { Route as PortalSplatRouteImport } from './routes/portal.$'
import { Route as ClientProjectsProjectIdRouteImport } from './routes/client.projects.$projectId'
import { Route as ClientProjectsNewRouteImport } from './routes/client.projects.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuilderRoute = AdminBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientActivityRoute = ClientActivityRouteImport.update({
  id: '/client/activity',
  path: '/client/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientFilesRoute = ClientFilesRouteImport.update({
  id: '/client/files',
  path: '/client/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientForgotPasswordRoute = ClientForgotPasswordRouteImport.update({
  id: '/client/forgot-password',
  path: '/client/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientInvoicesRoute = ClientInvoicesRouteImport.update({
  id: '/client/invoices',
  path: '/client/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMeetingsRoute = ClientMeetingsRouteImport.update({
  id: '/client/meetings',
  path: '/client/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientMessagesRoute = ClientMessagesRouteImport.update({
  id: '/client/messages',
  path: '/client/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientNotificationsRoute = ClientNotificationsRouteImport.update({
  id: '/client/notifications',
  path: '/client/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientOauthCallbackRoute = ClientOauthCallbackRouteImport.update({
  id: '/client/oauth-callback',
  path: '/client/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/client/payments',
  path: '/client/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/client/profile',
  path: '/client/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/client/projects',
  path: '/client/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRegisterRoute = ClientRegisterRouteImport.update({
  id: '/client/register',
  path: '/client/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRequirementsRoute = ClientRequirementsRouteImport.update({
  id: '/client/requirements',
  path: '/client/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientResetPasswordRoute = ClientResetPasswordRouteImport.update({
  id: '/client/reset-password',
  path: '/client/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/client/settings',
  path: '/client/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/client/support',
  path: '/client/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientVerifyEmailRoute = ClientVerifyEmailRouteImport.update({
  id: '/client/verify-email',
  path: '/client/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSplatRoute = PortalSplatRouteImport.update({
  id: '/portal/$',
  path: '/portal/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientProjectsProjectIdRoute = ClientProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ClientProjectsRoute,
} as any)
const ClientProjectsNewRoute = ClientProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/leads': typeof LeadsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/$': typeof AuthSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/files': typeof ClientFilesRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/oauth-callback': typeof ClientOauthCallbackRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/register': typeof ClientRegisterRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/reset-password': typeof ClientResetPasswordRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/client/verify-email': typeof ClientVerifyEmailRoute
  '/portal/$': typeof PortalSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/projects/$projectId': typeof ClientProjectsProjectIdRoute
  '/client/projects/new': typeof ClientProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/leads': typeof LeadsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/$': typeof AuthSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/files': typeof ClientFilesRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/oauth-callback': typeof ClientOauthCallbackRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/register': typeof ClientRegisterRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/reset-password': typeof ClientResetPasswordRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/client/verify-email': typeof ClientVerifyEmailRoute
  '/portal/$': typeof PortalSplatRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/client/projects/$projectId': typeof ClientProjectsProjectIdRoute
  '/client/projects/new': typeof ClientProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/leads': typeof LeadsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/builder': typeof AdminBuilderRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/$': typeof AuthSplatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/activity': typeof ClientActivityRoute
  '/client/files': typeof ClientFilesRoute
  '/client/forgot-password': typeof ClientForgotPasswordRoute
  '/client/invoices': typeof ClientInvoicesRoute
  '/client/login': typeof ClientLoginRoute
  '/client/meetings': typeof ClientMeetingsRoute
  '/client/messages': typeof ClientMessagesRoute
  '/client/notifications': typeof ClientNotificationsRoute
  '/client/oauth-callback': typeof ClientOauthCallbackRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/register': typeof ClientRegisterRoute
  '/client/requirements': typeof ClientRequirementsRoute
  '/client/reset-password': typeof ClientResetPasswordRoute
  '/client/settings': typeof ClientSettingsRoute
  '/client/support': typeof ClientSupportRoute
  '/client/verify-email': typeof ClientVerifyEmailRoute
  '/portal/$': typeof PortalSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/projects/$projectId': typeof ClientProjectsProjectIdRoute
  '/client/projects/new': typeof ClientProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/leads'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/builder'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website'
    | '/api/chat'
    | '/auth/$'
    | '/blog/$slug'
    | '/client/activity'
    | '/client/files'
    | '/client/forgot-password'
    | '/client/invoices'
    | '/client/login'
    | '/client/meetings'
    | '/client/messages'
    | '/client/notifications'
    | '/client/oauth-callback'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/register'
    | '/client/requirements'
    | '/client/reset-password'
    | '/client/settings'
    | '/client/support'
    | '/client/verify-email'
    | '/portal/$'
    | '/admin/'
    | '/client/'
    | '/client/projects/$projectId'
    | '/client/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/leads'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/builder'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website'
    | '/api/chat'
    | '/auth/$'
    | '/blog/$slug'
    | '/client/activity'
    | '/client/files'
    | '/client/forgot-password'
    | '/client/invoices'
    | '/client/login'
    | '/client/meetings'
    | '/client/messages'
    | '/client/notifications'
    | '/client/oauth-callback'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/register'
    | '/client/requirements'
    | '/client/reset-password'
    | '/client/settings'
    | '/client/support'
    | '/client/verify-email'
    | '/portal/$'
    | '/admin'
    | '/client'
    | '/client/projects/$projectId'
    | '/client/projects/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/leads'
    | '/portfolio'
    | '/pricing'
    | '/profile'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/builder'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/collections'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/website'
    | '/api/chat'
    | '/auth/$'
    | '/blog/$slug'
    | '/client/activity'
    | '/client/files'
    | '/client/forgot-password'
    | '/client/invoices'
    | '/client/login'
    | '/client/meetings'
    | '/client/messages'
    | '/client/notifications'
    | '/client/oauth-callback'
    | '/client/payments'
    | '/client/profile'
    | '/client/projects'
    | '/client/register'
    | '/client/requirements'
    | '/client/reset-password'
    | '/client/settings'
    | '/client/support'
    | '/client/verify-email'
    | '/portal/$'
    | '/admin/'
    | '/client/'
    | '/client/projects/$projectId'
    | '/client/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  LeadsRoute: typeof LeadsRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ClientActivityRoute: typeof ClientActivityRoute
  ClientFilesRoute: typeof ClientFilesRoute
  ClientForgotPasswordRoute: typeof ClientForgotPasswordRoute
  ClientInvoicesRoute: typeof ClientInvoicesRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientMeetingsRoute: typeof ClientMeetingsRoute
  ClientMessagesRoute: typeof ClientMessagesRoute
  ClientNotificationsRoute: typeof ClientNotificationsRoute
  ClientOauthCallbackRoute: typeof ClientOauthCallbackRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientProjectsRoute: typeof ClientProjectsRouteWithChildren
  ClientRegisterRoute: typeof ClientRegisterRoute
  ClientRequirementsRoute: typeof ClientRequirementsRoute
  ClientResetPasswordRoute: typeof ClientResetPasswordRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientSupportRoute: typeof ClientSupportRoute
  ClientVerifyEmailRoute: typeof ClientVerifyEmailRoute
  PortalSplatRoute: typeof PortalSplatRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/builder': {
      id: '/admin/builder'
      path: '/builder'
      fullPath: '/admin/builder'
      preLoaderRoute: typeof AdminBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/client/': {
      id: '/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/activity': {
      id: '/client/activity'
      path: '/client/activity'
      fullPath: '/client/activity'
      preLoaderRoute: typeof ClientActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/files': {
      id: '/client/files'
      path: '/client/files'
      fullPath: '/client/files'
      preLoaderRoute: typeof ClientFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/forgot-password': {
      id: '/client/forgot-password'
      path: '/client/forgot-password'
      fullPath: '/client/forgot-password'
      preLoaderRoute: typeof ClientForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/invoices': {
      id: '/client/invoices'
      path: '/client/invoices'
      fullPath: '/client/invoices'
      preLoaderRoute: typeof ClientInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/meetings': {
      id: '/client/meetings'
      path: '/client/meetings'
      fullPath: '/client/meetings'
      preLoaderRoute: typeof ClientMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/messages': {
      id: '/client/messages'
      path: '/client/messages'
      fullPath: '/client/messages'
      preLoaderRoute: typeof ClientMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/notifications': {
      id: '/client/notifications'
      path: '/client/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ClientNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/oauth-callback': {
      id: '/client/oauth-callback'
      path: '/client/oauth-callback'
      fullPath: '/client/oauth-callback'
      preLoaderRoute: typeof ClientOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/client/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/client/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/client/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/register': {
      id: '/client/register'
      path: '/client/register'
      fullPath: '/client/register'
      preLoaderRoute: typeof ClientRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/requirements': {
      id: '/client/requirements'
      path: '/client/requirements'
      fullPath: '/client/requirements'
      preLoaderRoute: typeof ClientRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/reset-password': {
      id: '/client/reset-password'
      path: '/client/reset-password'
      fullPath: '/client/reset-password'
      preLoaderRoute: typeof ClientResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/client/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/support': {
      id: '/client/support'
      path: '/client/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/verify-email': {
      id: '/client/verify-email'
      path: '/client/verify-email'
      fullPath: '/client/verify-email'
      preLoaderRoute: typeof ClientVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$': {
      id: '/portal/$'
      path: '/portal/$'
      fullPath: '/portal/$'
      preLoaderRoute: typeof PortalSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/projects/$projectId': {
      id: '/client/projects/$projectId'
      path: '/$projectId'
      fullPath: '/client/projects/$projectId'
      preLoaderRoute: typeof ClientProjectsProjectIdRouteImport
      parentRoute: typeof ClientProjectsRoute
    }
    '/client/projects/new': {
      id: '/client/projects/new'
      path: '/new'
      fullPath: '/client/projects/new'
      preLoaderRoute: typeof ClientProjectsNewRouteImport
      parentRoute: typeof ClientProjectsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBuilderRoute: typeof AdminBuilderRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBuilderRoute: AdminBuilderRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthSplatRoute: typeof AuthSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSplatRoute: AuthSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ClientProjectsRouteChildren {
  ClientProjectsProjectIdRoute: typeof ClientProjectsProjectIdRoute
  ClientProjectsNewRoute: typeof ClientProjectsNewRoute
}

const ClientProjectsRouteChildren: ClientProjectsRouteChildren = {
  ClientProjectsProjectIdRoute: ClientProjectsProjectIdRoute,
  ClientProjectsNewRoute: ClientProjectsNewRoute,
}

const ClientProjectsRouteWithChildren = ClientProjectsRoute._addFileChildren(
  ClientProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  LeadsRoute: LeadsRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ClientActivityRoute: ClientActivityRoute,
  ClientFilesRoute: ClientFilesRoute,
  ClientForgotPasswordRoute: ClientForgotPasswordRoute,
  ClientInvoicesRoute: ClientInvoicesRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientMeetingsRoute: ClientMeetingsRoute,
  ClientMessagesRoute: ClientMessagesRoute,
  ClientNotificationsRoute: ClientNotificationsRoute,
  ClientOauthCallbackRoute: ClientOauthCallbackRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientProjectsRoute: ClientProjectsRouteWithChildren,
  ClientRegisterRoute: ClientRegisterRoute,
  ClientRequirementsRoute: ClientRequirementsRoute,
  ClientResetPasswordRoute: ClientResetPasswordRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientSupportRoute: ClientSupportRoute,
  ClientVerifyEmailRoute: ClientVerifyEmailRoute,
  PortalSplatRoute: PortalSplatRoute,
  ClientIndexRoute: ClientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
